version: "3.8"

services:
  backend:
    container_name: back
    command : bash -c "python check_db.py --service-name db --ip db --port 3306 &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/settings.ini
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  app:
    container_name: app-front
    image: app-front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./src:/frontend/src
    command:
      - scripts/build.js
      - scripts/start.js
      - scripts/test.js

    ports:
      - 3000:3000